import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import * as esbuild from "esbuild";
import { webDarkTheme } from "@fluentui/tokens";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "assets", "vendor");
const ICON_DIR = join(HERE, "node_modules", "@fluentui", "svg-icons", "icons");

const ICONS = {
  add: "add_20_regular",
  arrowDown: "arrow_down_20_regular",
  arrowUp: "arrow_up_20_regular",
  book: "book_20_regular",
  calendar: "calendar_ltr_20_regular",
  chevronLeft: "chevron_left_20_regular",
  chevronRight: "chevron_right_20_regular",
  delete: "delete_20_regular",
  dismiss: "dismiss_20_regular",
  redo: "arrow_redo_20_regular",
  reset: "arrow_reset_20_regular",
  restore: "arrow_hook_up_left_20_regular",
  today: "calendar_today_20_regular",
  undo: "arrow_undo_20_regular",
};

const banner = (what) =>
  `/* Generated by web/build.mjs from ${what}. Do not edit by hand. */\n`;

async function buildComponents() {
  await esbuild.build({
    entryPoints: [join(HERE, "src", "fluent-entry.js")],
    outfile: join(OUT, "fluent.js"),
    bundle: true,
    format: "esm",
    target: "es2022",
    minify: true,
    legalComments: "none",
    banner: { js: banner("@fluentui/web-components").trim() },
  });
}

async function buildTheme() {
  const declarations = Object.entries(webDarkTheme)
    .map(([token, value]) => `  --${token}: ${value};`)
    .join("\n");
  await writeFile(
    join(OUT, "fluent-theme.css"),
    `${banner("@fluentui/tokens (webDarkTheme)")}:root {\n${declarations}\n}\n`,
  );
}

async function buildIcons() {
  const entries = [];
  for (const [name, file] of Object.entries(ICONS)) {
    const svg = await readFile(join(ICON_DIR, `${file}.svg`), "utf8");
    const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1];
    const body = /<svg[^>]*>([\s\S]*)<\/svg>/.exec(svg)?.[1];
    if (!viewBox || !body) throw new Error(`Cannot parse icon ${file}`);
    entries.push(`  ${name}: ${JSON.stringify({ viewBox, body })},`);
  }
  await writeFile(
    join(OUT, "fluent-icons.js"),
    `${banner("@fluentui/svg-icons")}export const ICONS = {\n${entries.join("\n")}\n};\n\n` +
      "export function icon(name, size = 20) {\n" +
      "  const { viewBox, body } = ICONS[name];\n" +
      '  return `<svg class="icon" width="${size}" height="${size}" viewBox="${viewBox}" ' +
      'fill="currentColor" aria-hidden="true">${body}</svg>`;\n' +
      "}\n",
  );
}

await mkdir(OUT, { recursive: true });
await Promise.all([buildComponents(), buildTheme(), buildIcons()]);
console.log("built assets/vendor/{fluent.js,fluent-theme.css,fluent-icons.js}");
